const orderData = [
  {
    id: 1,
    orderNumber: "001",
    customer: "John Doe",
    regularPrice: "₹400",
    salePrice: "₹350.00",
    orderStatus: "Completed",
    paymentStatus: "Paid",
    created: "2023-08-01",
  },
  {
    id: 2,
    orderNumber: "002",
    customer: "Jane Smith",
    regularPrice: "₹300",
    salePrice: "₹390.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 3,
    orderNumber: "002",
    customer: "Jane Smith",
    regularPrice: "₹500.38",
    salePrice: "₹449.00",
    orderStatus: "Completed",
    paymentStatus: "Pending",
    created: "2023-08-05",
  },
  {
    id: 4,
    orderNumber: "002",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 5,
    orderNumber: "002",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 6,
    orderNumber: "006",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 7,
    orderNumber: "002",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },

  {
    id: 8,
    orderNumber: "008",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 9,
    orderNumber: "008",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },
  {
    id: 10,
    orderNumber: "008",
    customer: "Jane Smith",
    regularPrice: "₹200.38",
    salePrice: "₹169.00",
    orderStatus: "Pending",
    paymentStatus: "Unpaid",
    created: "2023-08-05",
  },

  // Add more orders as needed...
];
export default orderData;
